controller_frequency: 10

TrajectoryPlannerROS:
  holonomic_robot: false
  yaw_goal_tolerance: 0.03
  xy_goal_tolerance: 0.05
  sim_time: 1.0
  meter_scoring: true
  pdist_scale: 0.6
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4 
  escape_vel: -1.0
